### ISSUE TITLE
I would like the agricolaeplotr plot to be colored by replication and treatment

### ISSUE THREAD

**Issue by dksam** [jensharbers/agricolaeplotr#1]
I would like the agricolaeplotr plot to be colored by replication and treatment, like if there are 7 treatments, with 7 colors and  3 replictions with 3 colors, with the label as 101, 102, 103 ... 107 (not 108, 109)

**Comment by jensharbers** [comment]
Hi, thank you very much using my package. Could you provide my the underlying function, please? Then I can look for a solution.

In general, to create a new factor in the outdesign object, you can paste two columns and assign them to a new variable. I do not have a computer at hand now,.so I type it by my.best on my phone.

Assuming using an alpha design, there are two columns, referecing to the replication and trt (Treatment). You can combine those factors into one using 

outdesign$book$combinded  
‹- paste(outdesign$book$replication , outdesign$book$trt)
.

Is it possoble to use two plots for both factors?
 So you can color one plot by trt and a separate one by the replication. Usually, field maps have one factors as a color

 In my plots I do not have for example.a specific alpha layer or one for a boundary. In case you need it, i can create a function that can be used in a quite less restricted manner.

Please let me.know.if my idea suits tonyour application.
