### ISSUE TITLE
{agricolaeplotr} vs. {desplot}?

### ISSUE THREAD

**Issue by SchmidtPaul** [jensharbers/agricolaeplotr#2]
Hi and thank you for creating {agricolaeplotr} - I just found out about it. So far, I have been using [{desplot}](https://github.com/kwstat/desplot) a lot and from a very first glance, I have the feeling that it is more flexible than {agricolaeplotr} - would you agree? However, as I demonstrate for a few examples [here](https://schmidtpaul.github.io/DSFAIR/DesigningExperiments.html), an extra step is usually needed to be able to plot designs created with {agricolae} via {desplot}.

Did I summarize this well or can you add some thoughts/details to this?

**Comment by jensharbers** [comment]
Hi Paul, thank you for your feedback. Agricolaeplotr does indeed have a different focus than desplot. If desplot is sufficient for plotting a design, feel free to use it. At the end of the vignette I already made the statement that desplot is a more flexible solution. With agricolaeplotr you have the advantage that you can specify the fields in area units and export the experimental designs for further processing in GIS applications. Some packages for GIS applications are also available in R. The trial designs from agricolae, however, do not always have all the necessary information to be able to display the design itself as a plot. As far as possible, the representation from my package represents that from agricolae. 

In CRAN the export function for the designs is not yet available, if desired I will be happy to update the package to CRAN.

P.S. In terms of flexibility, I have built a full_control function. This can accept and plot all designs with X and Y coordinates. 

Kind regards, Jens
