### ISSUE TITLE
Feature request: Wrap long labels used to identify plots

### ISSUE THREAD

**Issue by GilmourR** [jensharbers/agricolaeplotr#3]
Considering the function `plot_rcdb`, your nice package already gives the user the option of nominating the labels used to identify each plot (tile). However, if one uses the treatment names, and those names are long, the label will spill into the adjacent tiles. This could be addressed by providing the option to wrap the labels at a certain length of characters. For example, if the treatment names are in a column "treatments", this would be possible:
`table[, labels] <- stringr::str_wrap(table$treatments, width = label_width)`
where `label_width` is a user nominated label length where the label wraps.

Currently `plot_rcdb` uses `geom_text()` to label the plots (tiles), but you could use `geom_label()`, like this:
`geom_label(aes_string(label = labels), fill= "white", colour = "black")`.

We can easily also do:
 `p1 <- plot_rcdb()`
 `p1 + labs(title="My Title") + theme(legend.position="none")`
although the option to remove the legend could also be considered for this case where it becomes redundant.

With these changes , I was able to produce this, which I found very satisfying:
![image](https://github.com/jensharbers/agricolaeplotr/assets/13617073/c64b71ca-ebbe-4737-8752-9eefc004fd58)

Thanks for the nice package. It is very useful.

**Comment by jensharbers** [comment]
Hi GilmourR, I added some parts of your feature request. You may use the renamed function plot_rcbd (not plot_rcdb as this name was an missspelling and was pointed out by the active community as well). The function is now on github. The user has to define the label names in advances as those definitions are too individual to implement an one-fits-all function.
